services:
  - type: web
    name: codecorsa
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MYSQLHOST
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: MYSQLDATABASE
        sync: false
      - key: MYSQLPORT
        sync: false